// escolas.js - Lista de escolas de Navegantes-SC

export const escolasNavegantes = [
    { id: 1, nome: "C.M.E.I Prof.ª Maria da Silva Santos" },
    { id: 2, nome: "C.M.E.I Prof.ª Alciréia Conceição Couto" },
    { id: 3, nome: "C.M.E.I Prof.ª Julieta Pereira Muller" },
    { id: 4, nome: "C.M.E.I Prof.ª Recanto dos Baixinhos" },
    { id: 5, nome: "C.M.E.I Prof.ª Adélia de Souza Fernandes" },
    { id: 6, nome: "C.E.M Prof.ª Maria Regina Gazaniga da Costa" },
    { id: 7, nome: "C.E.M Prof.ª Bernadete Maria Sedrez da Silva" },
    { id: 8, nome: "C.E.M Prof.ª Elsir Bernadete Gaya Muller" },
    { id: 9, nome: "C.E.M Prof.ª Clarinda Maria Gaya" },
    { id: 10, nome: "C.E.M Prof.ª Maria de Lourdes Antunes" },
    { id: 11, nome: "C.M.E.I Prof.ª Alessandra Zilda da Silva" },
    { id: 12, nome: "E.M Prof.ª Neusa Maria Rebello Vieira" },
    { id: 13, nome: "E.M Prof.ª Rosa Maria Xavier de Araújo" },
    { id: 14, nome: "E.M Prof.ª Rosa Maria Xavier de Araújo – EXTENSÃO" },
    { id: 15, nome: "C.M.E.I Prof.ª Maria Carlota Vieira" },
    { id: 16, nome: "C.M.E.I Prof.ª Silvete Couto de Miranda" },
    { id: 17, nome: "E.M. Prof.ª Ilka Muller de Mello" },
    { id: 18, nome: "C.E.M. Prof.ª Leonora Schmitz" },
    { id: 19, nome: "C.M.E.I. Prof.ª Rosana de Fátima Gaya Barreto" },
    { id: 20, nome: "C.M.E.I. Prof.ª Regina Marly da Costa" },
    { id: 21, nome: "C.E.M. Prof.ª Eni Erna Gaya" },
    { id: 22, nome: "C.M.E.I. Portal do Saber" },
    { id: 23, nome: "C.M.E.I. Prof.ª Maria das Neves Emílio" },
    { id: 24, nome: "Pré E.M. Prof.ª Nazir Rodrigues Rebello" },
    { id: 25, nome: "E.M. Prof.ª Vilna Correa Pretti" },
    { id: 26, nome: "C.M.E.I. Prof.ª Natalina Sabel do Amaral" },
    { id: 27, nome: "C.M.E.I. Prof.ª Maria de Lourdes Couto Cabral" },
    { id: 28, nome: "C.E. Prof.ª Maria de Lourdes Couto Cabral – CAIC" },
    { id: 29, nome: "C.M.E.I. Prof.º Robson Francisco Lopes" },
    { id: 30, nome: "C.M.E.I. Prof.ª Laci Ana de Borba Cesário" },
    { id: 31, nome: "C.M.E.I. Prof.ª Maria dos Navegantes Ramos" },
    { id: 32, nome: "E.M. Prof.ª Izilda Reiser Mafra" },
    { id: 33, nome: "E.M. Prof.ª Idília Machado Ferreira" },
    { id: 34, nome: "C.M.E.I. Prof.ª Isabel Flores Pagani" },
    { id: 35, nome: "C.M.E.I. Prof.ª Kátia Regina Gazaniga de Souza" },
    { id: 36, nome: "C.M.E.I. Prof.º José dos Passos Lemos" },
    { id: 37, nome: "E.M. Prof.ª Maria Tereza Leal" },
    { id: 38, nome: "E.M. Prof.ª Vergina Guedes Lemos" },
    { id: 39, nome: "E.M. Prof.ª Maria Hostim da Costa" },
    { id: 40, nome: "C.M.E.I. Prof.ª Nerozilda Pinheiro Ferreira" },
    { id: 41, nome: "C.E.M. Prof.ª Giovana Soares da Cunha" },
    { id: 42, nome: "C.E.M. Prof.ª Giovana Soares da Cunha (Cidade da Criança)" },
    { id: 43, nome: "C.E.M. Prof.ª Didymea Lazzares de Oliveira" },
    { id: 44, nome: "E.M. Prof.ª Maria Ivone Muller dos Santos" },
    { id: 45, nome: "C.M.E.I. Bruce Craston Kay" },
    { id: 46, nome: "C.E.M. Prof.ª Badia de Faria" }
];

